name: Build and Test

on: [push]

jobs:

  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:

    - name: Set up Go 1.15
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Checkout
      uses: actions/checkout@v2

    - name: Download dependencies
      run: go mod download

    - name: Run tests
      run: go test -v -race ./...
